### ISSUE TITLE
Post Announcement on Tiller Community Forum

### ISSUE THREAD

**Issue by GregSweats** [trxn8r/trxn8r#15]
## TODO

- [ ] Record Demo Video
- [ ] Add Demo Video to YouTube Playlist
- [ ] Add Demo Video to /README.md
- [ ] Draft Post in Obsidian
- [ ] Post

**Comment by GregSweats** [comment]
https://community.tillerhq.com/search?q=User%20Request

**Comment by GregSweats** [comment]
Posted last night.

https://community.tillerhq.com/t/trxn8r-a-bulk-csv-importer-for-excel-powered-by-power-query/12897
